services:
  postgres:
    image: postgres:16
    container_name: medium-postgres
    environment:
      POSTGRES_DB: medium
      POSTGRES_USER: kritsana
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - medium-network

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    entrypoint: [
      "sh", "-c",
      "sleep 5; until nc -z medium-postgres 5432; do echo waiting for postgres; sleep 2; done; \
      migrate -source file://./migrations -database 'postgres://kritsana:123456@medium-postgres:5432/medium?sslmode=disable&TimeZone=Asia/Bangkok' up"
    ]
    volumes:
      - ./scripts/migrate:/migrations
    networks:
      - medium-network


volumes:
  postgres_data:

networks:
  medium-network:
    driver: bridge